# CMake generated Testfile for 
# Source directory: /mnt/c/Ryute/Univ2022/sixcurity_back/restinio-0.6.17/dev/test
# Build directory: /mnt/c/Ryute/Univ2022/sixcurity_back/restinio-0.6.17/dev/cmake_build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("catch_main")
subdirs("metaprogramming")
subdirs("tuple_algorithms")
subdirs("utf8_checker")
subdirs("http_field_parser")
subdirs("try_parse_field")
subdirs("multipart_body")
subdirs("default_constructed_settings")
subdirs("ref_qualifiers_settings")
subdirs("header")
subdirs("buffers")
subdirs("response_coordinator")
subdirs("write_group_output_ctx")
subdirs("uri_helpers")
subdirs("socket_options")
subdirs("start_stop")
subdirs("handle_requests")
subdirs("run_on_thread_pool")
subdirs("http_pipelining")
subdirs("sendfile")
subdirs("router")
subdirs("transforms/zlib")
subdirs("transforms/zlib_body_appender")
subdirs("transforms/zlib_body_handler")
subdirs("encoders")
subdirs("from_string")
subdirs("websocket")
subdirs("file_upload")
subdirs("basic_auth")
subdirs("bearer_auth")
subdirs("socket_options_tls")
